### ISSUE TITLE
NA values for small polygons

### ISSUE THREAD

**Issue by karlozfp** [isciences/exactextract#10]
Thanks for your great contribution!!. 
exact_extract works very fast in comparison to other packages however I  am getting NA values for very small polygons that are covered by one pixel. Is there something to do about it in exact_extract function?

**Comment by dbaston** [comment]
This should work without problems. Do you have some test data you can share?

**Comment by karlozfp** [comment]
Sorry, it was a mistake since particular pixels resulted to have NA values.
