### ISSUE TITLE
error using Docker

### ISSUE THREAD

**Issue by iferencik** [isciences/exactextract#106]
I am running the dockerized version of extractextact on a global vector layer  and a COG computimng mean, both in EPSG:3857 projection. Unfortunately the programs stops with the message

**Error: unordered_map::at**

nothing else

I tried reprojecting both to WGS84 but to no avail.

any hints are appreaciated

**Comment by dbaston** [comment]
Can you share your inputs and the command you're using?

**Comment by iferencik** [comment]
sure 

i have created a local command to lauch docker

```bash
cat /usr/local/bin/exactextract
docker run --rm -it -u 1000 -v /data:/data -v /work:/work isciences/exactextract:latest  "$@"
exactextract -p /data/hrea/admincgaz/geoBoundariesCGAZ_ADM03857.fgb -r hrea_2012:/data/hrea/1km/Electricity_access_estimate_2012_un.tif -f id -s "hrea_2012=mean(hrea_2012)" -o /data/hrea/out/a0.csv
Error: unordered_map::at

cat out/a0.csv 

id,hrea_2012
"154",0.127339616417885
"75",-nan
"179",0.122186340391636
"123",0.453419029712677


```


the raster and vector are in gogole web mercator

**Comment by iferencik** [comment]
i logged in into the contaienr and run the command directly...same error

**Comment by dbaston** [comment]
It looks like the image on Docker Hub hasn't been updated in several months. This may be something that has been fixed since then. You could try building the Docker image based on the Dockerfile in the repo.

**Comment by iferencik** [comment]
> I just restored automatic Docker builds, so you can try running with `isciences/exactextract:master` to see if that fixes it.

@dbaston thanks,

i built it locally and it works
Iredownloaded the remote one and it failed. I think it might be cached for some time
will retry in 1 hour and let you know

**Comment by iferencik** [comment]
i can confirm now everything works
i am closing the issue
