### ISSUE TITLE
problem with python, error:  Never get here.

### ISSUE THREAD

**Issue by automataIA** [isciences/exactextract#126]
Hi.

The problem I have is when I run this line of code
```python
raster_file = 'tif/33TWF.tif'  # GeoTiff
vector_file = 'shp/33TWF.shp' #  Shapefile extracted with pgsql2shp
stats = exact_extract(raster_file, vector_file, ["count", "mean"])`
```
gives me this error:
```bash
............../lib/python3.10/site-packages/exactextract/exact_extract.py", line 320, in exact_extract
    processor.process()
RuntimeError: Never get here.
```
this is the link to the raster (if it helps): https://we.tl/t-Vn66czZl8w

Context:
 I'm extracting a shapefile from a postigis DB with ewkb and it had never given me this problem the previous times.
 I checked both SRIDs (UTM coordinates) 32633 of the two files and they match.

**Comment by dbaston** [comment]
Are you able to share the shapefile?

**Comment by dbaston** [comment]
If you run the same process from the command line, the progress output may help you identify the problem polygons. Or in Python, instead of providing the filename to `exact_extract`, you could provide a GeoPandas data frame with individual polygons until you find the problem. But if you're not able to share the polygon that's causing the problem, I don't think there is much I can do to fix it.

**Comment by dbaston** [comment]
> I tried both methods, and they don't give me extra output.

There is no extra output from the GeoPandas version. What I was suggesting was a way to subset your data to identify the problem polygon. 

Alternatively, to get extra output from the CLI, use `--progress` with `--include-col`, e.g:

```
./exactextract --polygons concelhos.gpkg --raster clc2018_v2020_20u1.tif --include-col name --output /tmp/out.csv --progress --stat mode
```

This will display progress information:

```
Processing Lagoa.
Processing Nordeste.
Processing Ponta Delgada.
Processing Povoação.
Processing Ribeira Grande.
Processing Vila Franca do Campo.
````

so the last "Processing" entry before the error can be used to identify the input that is causing the problem.

**Comment by dbaston** [comment]
You need to use `--include-col`, see above

**Comment by dbaston** [comment]
What does `ogrinfo -al -so shp/zsd.shp` return?
