### ISSUE TITLE
Emit error or automatically reproject on CRS mismatch

### ISSUE THREAD

**Issue by yash-jain16** [isciences/exactextract#14]
**Running in mac terminal after running docker**
exactextract -r lat:sample.tif[1] -p Block-polygon.shp -f District -s mean(lat) -o minimum.csv

bash: syntax error near unexpected token `('

**Running in Docker container cli**

 exactextract -r lat:sample.tif -p Block-polygon.shp -f District -s mean(lat) -o minimum.csv

/bin/sh: 1: Syntax error: "(" unexpected

**Comment by dbaston** [comment]
Wrap your arguments in quotes: `exactextract -r "lat:sample.tif[1]" -p Block-polygon.shp -f District -s "mean(lat)" -o minimum.csv`

**Comment by yash-jain16** [comment]
Thanks for this, but the retrieved CSV file has no value in it. It gives the following output:
![image](https://user-images.githubusercontent.com/47213889/82075351-bb342000-96f9-11ea-937b-288cbe15f739.png)

**Comment by yash-jain16** [comment]
docker run --rm -it exact:tag -r "lat:/<path>/sample.tif[1]" -p /<path>/Block-polygon.shp -f District -s "min(lat)" -o /<path>p/minimum.csv

ERROR 4: /<path>/sample.tif: No such file or directory
Error: Failed to open /<path>/sample.tif

**Error when executing through ENTRYPOINT**

**Comment by dbaston** [comment]
You need to expose your inputs to Docker; add `-v /path_to_file:/path_to_file` to your `docker run` command.

**Comment by yash-jain16** [comment]
Thanks for all your help, actually I was able to run the code but the output csv file has no value in it. It does create the columns but there are no values for any of the operations(mean,min,etc...)
![image](https://user-images.githubusercontent.com/47213889/82182589-22bcbc00-9902-11ea-9226-f82cc638d72b.png)
Could you please guide me as to where I would be going wrong.

**Comment by dbaston** [comment]
Can you share the inputs?

**Comment by yash-jain16** [comment]
[Archive.zip](https://github.com/isciences/exactextract/files/4647871/Archive.zip)
The zip contains the input file as sample.tif and the shapefile in .shp format. 
_-r "lat:sample.tif[1]" -p Block-polygon.shp -f District -s "min(lat)" -o minimum.csv_
These were the parameters passed.

**Comment by dbaston** [comment]
The results are empty because exactextract assumes that all of its inputs are in the same coordinate system (and these are not). Ideally it would detect this and emit an error (or reproject itself) but it doesn't currently.

**Comment by yash-jain16** [comment]
Thank you soo much! Works like a charm.
