### ISSUE TITLE
Add support to specify a list of images to calculate statistics on to python API

### ISSUE THREAD

**Issue by theroggy** [isciences/exactextract#157]
Be able to use the optimization that the pixel fractions only need to be calculated once for multiple images following the same grid.

**Comment by dbaston** [comment]
This is already supported, unless I'm misunderstanding...

https://github.com/isciences/exactextract/blob/5b372a6bc03205e1cfe8197c39c17b195f227072/python/tests/test_exact_extract.py#L363-L375

**Comment by theroggy** [comment]
Ah, great! Thanks!
