### ISSUE TITLE
Typo in the requirements

### ISSUE THREAD

**Issue by kasra-keshavarz** [isciences/exactextract#31]
I've noticed that in the requirements section of the compilation, it is mentioned that CMake 3.8+ is needed; the latest version of the CMake is 3.23.2 as of May 25th 2022.

**Comment by dbaston** [comment]
Do you mean that the `CMakeLists.txt` is using a feature not available in CMake 3.8?

**Comment by kasra-keshavarz** [comment]
Oh sorry I think I made a mistake here. Please disregard this issue.
