### ISSUE TITLE
Support for LineStrings

### ISSUE THREAD

**Issue by jdalrym2** [isciences/exactextract#35]
What sort of work would need to be done to support LineString geometry types? Theoretically this should be possible: instead of area overlap of a cell, you'd instead by looking at the length of the line in the cell and computing stats based on that.

Currently to work with LineString geometries I run a tiny buffer operation to get Polygon geometries as input, but ideally I'd skip this step and be able to use LineString geometries directly.

Thanks!

Jon

**Comment by jdalrym2** [comment]
Yes, that's correct. In my use case I'm mainly interested in mean atm ($C_i$ -> value of cell $i$, $L_i$ -> line length in cell $i$):
$$\frac{1}{L_{tot}} \left( C_1L_1 + C_2L_2 + \cdots + C_nL_n \right)$$
or a weighted sum (same thing as the mean but don't divide by line length, i.e. a line integral).

Looking at the table in the README a lot of stats could be useful (min, max, minority, majority, variety, stddev), but those are little more down the road for me.

Also happy to help out, but would likely need some guidance on implementation.

**Comment by dbaston** [comment]
If you'd like, you could do some testing on this branch: https://gitlab.com/isciences/exactextract/-/tree/linestring-overlap-length-2 which has LineString support rebased onto the current master branch.

**Comment by dbaston** [comment]
Completed in d3974b09f507ef9a9bead870e15bb5ce163c5e51
