### ISSUE TITLE
Outputting the remapping information

### ISSUE THREAD

**Issue by ShervanGharari** [isciences/exactextract#41]
Thank you for `exactextract`!
I was wondering if it's possible to also have the remapping information outputted. For instance, I would like to know which row and columns, along with their latitude and longitude, correspond to which shape ID in the shapefile. This would be a valuable addition. Has this been implemented in `exactextract` already?
Thank you for considering my request in advance.

**Comment by dbaston** [comment]
This can now be done using `coverage(raster_name)`.
