### ISSUE TITLE
Missing Fraction Statistic 

### ISSUE THREAD

**Issue by AlaBahrami** [isciences/exactextract#46]
Hi, 

Thanks a lot for providing this useful package. It is very useful and quick. 
I am wondering if there is any way to add the `frac` function to the list of operations. I see in the `exactextractr` package you have it, but it is missing here. It would be quite useful also to have this one in the list of zonal statistic functions. 

Thanks

**Comment by dbaston** [comment]
This is now available with 55423b52011f6cfd0ee0e423b9dfa05f58e9fb0a
