### ISSUE TITLE
Python: availability on PyPI

### ISSUE THREAD

**Issue by martinfleis** [isciences/exactextract#84]
Hi,
Thanks a lot for the work on Python bindings. I am wondering if there are some plans to publish the package on PyPI (and possibly conda-forge but I'm happy to help with that on PyPI is available)? I'd like to use `exactextract` as alternative backend on zonal stats functionality of [`xvec`](https://github.com/xarray-contrib/xvec) but for that would assume that users can just pip install the wheel.

I am completely aware that Python packaging and wheel building is a pain so I understand if you don't want to go that way but it'd be nice top know what the situation is. 

Thanks!

**Comment by JakubCha** [comment]
Hi Dan, Martin,
I would also like to see the package published on PyPI as it would greatly help me to push QGIS plugin ([exactextract_qgis](https://github.com/JakubCha/exactextract_qgis)) I created recently into production state.

Thank you

**Comment by dbaston** [comment]
I'm happy to publish wheels to PyPI if I can figure out how to do so. I'm intending to look into [cibuildwheel](https://github.com/pypa/cibuildwheel) but haven't got to it yet.

**Comment by vincentsarago** [comment]
FYI: I've started some exploratory work with cibuildwheel over https://github.com/vincentsarago/exactextract/pull/1

**Comment by dbaston** [comment]
Wow, thank you @vincentsarago !

**Comment by vincentsarago** [comment]
Well to be honest, I ended up copy/pasting most of https://github.com/shapely/shapely/blob/e344003a4a2c9002986f54e03e30fed645f7f2ac/.github/workflows/release.yml#L49-L157 😅

**Comment by dbaston** [comment]
A development snapshot is available at https://pypi.org/project/exactextract/0.2.0.dev0/
